pipeline {
    agent any

    tools {
        python 'Python3' // Set this up under Manage Jenkins > Global Tool Configuration
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/felikz97/alx-backend-python.git'
            }
        }

        stage('Install dependencies') {
            steps {
                sh 'pip install -r messaging_app/requirements.txt'
            }
        }

        stage('Run tests') {
            steps {
                sh 'pytest messaging_app --junitxml=test-report.xml'
            }
        }

        stage('Publish test report') {
            post {
                always {
                    junit 'test-report.xml'
                }
            }
        }
    }
}
