#!/bin/bash

echo " Deploying blue version..."
kubectl apply -f blue_deployment.yaml

echo " Deploying green version..."
kubectl apply -f green_deployment.yaml

echo " Updating service to point to green version..."
kubectl apply -f kubeservice.yaml

echo " Waiting for green pod to start..."
sleep 5

echo " Checking logs of green version pod..."
GREEN_POD=$(kubectl get pods -l version=green -o jsonpath="{.items[0].metadata.name}")
kubectl logs $GREEN_POD
