apiVersion: v1
kind: Service
metadata:
  name: messaging-app-service
spec:
  selector:
    app: messaging-app
    version: green  # Switch this to "blue" or "green" to route traffic
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

selector:
  app: messaging-app
  version: blue
