apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messaging-app
  template:
    metadata:
      labels:
        app: messaging-app
    spec:
      containers:
        - name: messaging-app
          image: messaging_app:latest  # Replace with full Docker Hub path if needed
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: "localhost"  # Replace this if using an external DB or another pod
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "messaging_db"
            - name: DB_USER
              value: "messaging_user"
            - name: DB_PASSWORD
              value: "securepassword"

---

# ClusterIP Service (internal only)
---
apiVersion: v1
kind: Service
metadata:
  name: messaging-app-service
spec:
  selector:
    app: messaging-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
