pipeline {
    agent any

    tools {
        python 'Python3' // must match Global Tool Configuration
    }

    environment {
        // Make sure this matches the ID of your GitHub credentials in Jenkins
        GITHUB_CREDENTIALS = 'your-credentials-id'
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main',
                    credentialsId: "${GITHUB_CREDENTIALS}",
                    url: 'https://github.com/felikz97/alx-backend-python.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'pip3 install -r messaging_app/requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'pytest messaging_app --junitxml=report.xml'
            }
        }

        stage('Publish Test Report') {
            post {
                always {
                    junit 'report.xml'
                }
            }
        }
    }
}
